spring:
  application:
    name: AuthenticationAPI
  security:
    user:
      name: USER001
      password: 122345
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8081
jwt:
  secret: ${JWT_SECRET}
  expiration: 1800000
role:
  server:
    url: ${ROLE_SERVER_URL}


